FROM golang:1.19-bullseye AS builder

RUN apt update -qq \
    && apt install -y --no-install-recommends -qq \
    build-essential make curl wget \
    && apt clean \
    && apt autoclean -y -qq\
    && apt autoremove -y -qq\
    && rm -rf /var/lib/apt/lists/*

WORKDIR /app

COPY go.mod go.sum ./

RUN go mod download && go mod verify

RUN go install github.com/cosmtrek/air@latest

COPY ./ ./app

CMD ["air", "-c", ".air.toml"]